### ISSUE TITLE
On home page, only show control panel button for an admin user

### ISSUE THREAD

**Issue by jamiecoe** [FACN7/feelit-chips-frontend#45]
On home page, you need to check if user is an admin - you can do this using the response from `GET /check-auth` (see #10).

If the user is an admin, you should display a Control Panel button. When clicked this Control Panel button will take the user to the Control Panel page. 

See #22 for Control Panel icon

**Comment by ebraheemabbas** [comment]
sorry kira . seems i did this issue with the control panel branch
